### ISSUE TITLE
Foto-Upload funktioniert nicht mehr

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/viszerale-therapie.at#37]
Es können keine Fotos mehr hochgeladen werden. Ich habs grad getestet. 
Das Upload-Fenster wird nicht mehr angezeigt. 
![bild-upload](https://user-images.githubusercontent.com/23695891/41477344-3a104150-70c4-11e8-91c7-f628f9a78def.png)

**Comment by ursulafeu** [comment]
PS: Kannst Du Dir das bitte relativ rasch ansehen. Ich müsste nämlich Kurse abschließen und die Leute zur Therapeutenliste einladen ... danke! :)

**Comment by Andreas-Schoenefeldt** [comment]
si :)

**Comment by ursulafeu** [comment]
danke schon mal :)

**Comment by Andreas-Schoenefeldt** [comment]
Ok, also bei mir lokal geht alles - ich prüfe jetzt nochmal live.

**Comment by Andreas-Schoenefeldt** [comment]
Ist ein http auf https issue, ich behebe das:
<img width="1326" alt="screen shot 2018-06-18 at 15 33 35" src="https://user-images.githubusercontent.com/1157580/41539068-1e64635a-730d-11e8-94c6-8401b6bec31d.png">

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

ich denke ich hab es jetzt gefunden. Kannst du das bitte einmal live versuchen? Ich traue mich nicht ein echtes Bild zu überschreiben.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Fotoupload funktioniert wieder, danke!
Die PLZ Umkreissuche funktioniert jetzt auch wieder, oder?

**Comment by Andreas-Schoenefeldt** [comment]
An der PLZ suche habe ich meines Wissens nichts geändert - kann auch sein, das es nur für manche nicht geht… Wenn man das wirklich gut machen wollte, müsste ich das ganze feature einmal aufbohren, was glaube ich nicht im budget ist.

Liebe Grüße
Andreas

**Comment by multireadsts** [comment]
Also ich finde dass das feature richtig gut funktioniert ;)

**Comment by ursulafeu** [comment]
ja seltsam ... die PLZ Suche funktioniert wieder. Vielleicht lag das auch am SSL, wie auch immer. Augen zu und weitermachen. ;)
