### ISSUE TITLE
Fehler in Suche

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/viszerale-therapie.at#38]
It is basically this issue: https://github.com/viszerale-therapie/simple-courses/issues/158

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, das sollte jetzt wieder wie erwartet funktionieren - die postleitzahlen suche hatte sich irgendwie auf Luxemburg eingeschossen gehabt ;)

**Comment by ursulafeu** [comment]
danke, funktioniert!
