### ISSUE TITLE
Darstellungsfehler in Chrome

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/viszerale-therapie.at#39]
Lieber Andreas, auf PC und Chrome erscheinen eigenartige Zeichen auf dieser Seite:
https://viszerale-therapie.at/ueber-uns/leitbild 
- siehe Screenshot

Kannst Du das bitte checken, ich hatte das vor einiger Zeit mal per Email geschickt. danke!
![2018-10-09 09_11_11-leitbild _ schule fur viszerale therapie](https://user-images.githubusercontent.com/23695891/48676950-356bfe80-eb6e-11e8-9aa8-0728672a2104.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

da ist irgend ein "unsichtbares" Steuerzeichen mit rein gerutscht. Ich denke, das es etwas damit zu tun hat, das der Text aus Word oder so kopiert wurde.

Wenn du in den Quelltext-Modus schaltest und mit den Pfeiltasten etwas hin und her gehst, gibt es dort eine Stelle, die ein Zeichen enthält, das aber nicht sichtbar ist. Wenn du das löschst sollte die Darstellung wieder ok sein:

<img width="401" alt="screen shot 2018-11-19 at 14 15 43" src="https://user-images.githubusercontent.com/1157580/48694996-f9847800-ec05-11e8-9a4d-96cc0e5225fc.png">

Auf dem Mac kann ich es nicht einmal sehen - ich denke das ist zusätzlich ein Windows only Problem ;)

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke Andreas! 👍

Von meinem iPhone gesendet
