### ISSUE TITLE
Fehler bei der Registrierung, wenn ' im Text mit angegeben wird

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/viszerale-therapie.at#40]
> Guten Tag,
> ich habe einige Male versucht mich neu zu registrieren. Leider bekam ich jedes mal folgende Meldung:
> 
> Aufgrund eines Fehlers konnten wir Ihren Eintrag nicht anlegen: INSERT INTO `tl_therapeuten` > (tp_anrede, tp_titel, tp_nachname, tp_vorname, foto, tp_beruf_de, tp_beruf_en, tp_beruf_ru, praxisbezeichnung, strasse, plz, ort, land, telefon, email, web, passwort, ausbildungsid, aktiv) VALUES ('Frau','','B','J', '', 'Physiotherapeutin', '', '', 'X'und in Form','Gugenedt 4',4741,'Wendling','Österreich','1111','...@gmx.at','http://www.xund-in-form.at/','9856Quaoar',0, 0)
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server > version for the right syntax to use near 'und in Form','Gugenedt 4',4741,'Wendling','Österreich','0660/9031977','Jolanda.' at line 2
>
> Vielleicht könnten Sie mir weiterhelfen, um in die Liste aufgenommen zu werden. Ich habe bereits mehrere Kurse absolviert, aber mich noch nie registrieren lassen.
> Freue mich auf Ihre Antwort. Vielen Dank im Voraus!

Es fehlt ein mysql escape

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

der Fehler ist jetzt behoben und sonderzeichen sollten die mysql query nicht mehr zerstören können ;) - eine kleine Verbesserung.

Du kannst Frau Breuer schreiben, das Sie es noch einmal versuchen kann oder den Eintrag in ihrem Namen anlegen.

Liebe Grüße
Andreas

**Comment by multireadsts** [comment]
Danke :)
