### ISSUE TITLE
Therapie List - Link to new Course detail pages

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/viszerale-therapie.at#6]
>  Therapeutenliste: Verlinkung auf die neuen Seminarseiten auf der Übersicht und in der Detailansicht unter eventueller Berücksichtigung der Punkte von oben. Ich würde versuchen, hier eventuell an dein neues Datenmodell anzukoppeln.

**Comment by multireadsts** [comment]
What I meant were the links from therapeutenliste (the small buttons) to the new course list. 
I will fix that after the links in the course list are more search engine compatible.
