### ISSUE TITLE
Remove Passwords from repository

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/viszerale-therapie.at#8]
I moved passwords from the following files to `inc\config\settings.php`

```
/therapeuten_aktivieren.php line 27 : if ($pass == TL_PASSWORD) {
/therapeuten_update.php line 23: if ($_GET['passwort'] == TL_PASSWORD) {
/therapeut_loeschen.php
/inc/pw_inc.php : [...] and $_GET['passwort'] != TL_PASSWORD
inc/mailaccount.php : All passwords moved
```

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stefan, could you please shortly check on http://lotus-moon.de/Proj/viszerale-therapie.at/index.php?lang=de if the therapeutenliste is still working?

Thx a lot
Andreas

**Comment by multireadsts** [comment]
No it isn't. Did you pull the pear library from the webspace?

**Comment by multireadsts** [comment]
Password Feedback:
Still in plaintext and not TL_Password on
https://github.com/Andreas-Schoenefeldt/viszerale-therapie.at/blob/master/therapeuten_update.php

line23 or f.e.
https://github.com/Andreas-Schoenefeldt/viszerale-therapie.at/blob/master/therapeut_loeschen.php

Still not uploaded from local server?

Liebe Grüße,
Stefan

**Comment by Andreas-Schoenefeldt** [comment]
Hi Stefan, I made another commit and will deploy the update now on the server - I found a few other places, where the password was used, also in some email links as I found - it should now all out :)

Best wishes
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Seems to work :)
